#!/bin/bash

# USERS MUST CHANGE THESE !!!!!!
export SWIFT_DIR=THE-DIRECTORY

. ${SWIFT_DIR}/@DefineCompiler

# To Profile the code:
#export FFLAGS='-G -c'

echo Using "$FORTRAN" Compiler

for file1 in *.f; do
    file2=${file1/.f/}
    echo $file2
    $FORTRAN $FFLAGS -c "$file2".f
    ar vr $SWIFT_DIR/libswift.a  "$file2".o
done

\rm *.o
echo Done directory $PWD 
